### ISSUE TITLE
Localize MacVim and add translations

### ISSUE THREAD

**Issue by ychin** [macvim-dev/macvim#1102]
This issue is used to serve as a master issue to track the ongoing work to localize MacVim.

Messages:
- [x] Support Vim message translation / `:set lang` (#1070)
- [ ] Add MacVim-specific translations for MacVim-specific messages.

Menus
- [x] Support Vim menu translations / `:set langmenu` (#1099)
- [x] Add Apple official translations for common menu names like "Copy" or "Font" that MacVim uses (#1099)
- [ ] Translate remaining menu items.

User Interface (e.g. preference pane)
- [ ] Need translations.

Help documentation (`:help macvim` / `gui_mac.txt`)
- [ ] Need translations

**Comment by ychin** [comment]
One option is to use Crowdin to manage the localization if it's easier for contributors. We don't really have enough strings to justify such effort though.
