### ISSUE TITLE
CI: Migrate to GitHub Actions

### ISSUE THREAD

**Issue by ychin** [macvim-dev/macvim#1127]
Due to Travis CI's [recent changes](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) which makes it harder for open-source projects to run for free, we should investigate migrating to Github Actions (which a lot of other open-source apps have done as well). We currently have a limited set of credits which will run out soon, so we should do the work soon.

Also, GitHub Actions supports more features than Travis CI, such as the ability to generate artifacts, much better control over caching, flexible language for constructing different jobs and tasks, tighter integration with other GitHub features like releases, and so on.

The loss here would be the test matrix as Travis CI has a [much wider range](https://docs.travis-ci.com/user/reference/osx/) of macOS VMs to choose from (down to Xcode 7 / macOS 10.11 as of now), whereas GitHub Actions is [much more limited](https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners) for testing on old OS versions (down to Xcode 10 / macOS 10.15 only).

Track that work in this issue.

- [x] Add GitHub Actions support (#1144)
- [x] Fix Vim tests to work (#1146)
- [x] Add test matrix (#1147)

**Comment by ychin** [comment]
This is done and it basically working. Could always add more to it in the future.
